// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuotesAPI.Data;

#nullable disable

namespace QuotesAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250310025625_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QuotesAPI.Models.Quote", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("No"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Premium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("QuoteType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sales")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("No");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            No = 1,
                            Description = "This is auto insurance",
                            DueDate = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Premium = 240.00m,
                            QuoteType = "Auto",
                            Sales = "John"
                        },
                        new
                        {
                            No = 2,
                            Description = "This is auto insurance",
                            DueDate = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Premium = 240.00m,
                            QuoteType = "Auto",
                            Sales = "John"
                        },
                        new
                        {
                            No = 3,
                            Description = "This is auto insurance",
                            DueDate = new DateTime(2011, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Premium = 300.00m,
                            QuoteType = "Auto",
                            Sales = "Mary"
                        },
                        new
                        {
                            No = 4,
                            Description = "This is house insurance",
                            DueDate = new DateTime(2013, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Premium = 116.00m,
                            QuoteType = "House",
                            Sales = "John"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
